spring:
  config:
    import: optional:file:env.properties
  datasource:
    url: ${DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: ${HOST}
    port: ${PORT}
    username: ${HOTEL.USERNAME}
server:
  port: 8080